os: osx
osx_image: xcode11.6
language: objective-c


script:
- set -o pipefail
- xcodebuild -project Samples/HCPush.xcodeproj -scheme HCPush -configuration Release -sdk iphonesimulator -arch x86_64 clean build | xcpretty


