os: osx
osx_image: xcode11.6
language: objective-c

before_install:
- chmod +x scripts/travis/add-key.sh
- cd $TRAVIS_BUILD_DIR
- openssl aes-256-cbc -K $encrypted_325e42e71f12_key -iv $encrypted_325e42e71f12_iv
  -in certificates.tar.enc -out certificates.tar -d
- tar xvf certificates.tar -C ./scripts/travis/certificates

before_script:
- "./travis/scripts/add-key.sh"

script:
- set -o pipefail && xcodebuild -project Samples/HCPush.xcodeproj -scheme HCPush -sdk
  iphoneos -configuration Release | xcpretty
  
env:
  global:
    secure: EjENUJrtmWR9ks38rNQvum6ljD1cmFJcL59a9l2pSZdpg5aZLlU9qmlkbtE1a+tYy5aUqjexLmBNGlF5qEp6V0vYcWSkUD7+3NbVnF7uSR+qqy5aMBCdq2gO0bM3AJgIZYfmJpS23QDxyUoDCng+AwyzhqNbFBoOh9RbABDIGljWYa61fRiofAkE68XooFHmwW84R8/4TMSIHBIMFXYrKdvO2sBH/Sl5Ig2nmVN83Guv+p7B+ISXkkRjw/+r+tqmPB3Oj0gRBP7nfKId7FTbGm+AyZ+xGBkoSVzddWwOderkXHk/7zgsZhD3OKF/MtVDXgv0355+JcWDFvSgd2wtUJoSL1CJd+Y0hVfEdatf9MaL9BfCG9yxDMJUtph7upXlGaBqo2N1fPQM3JAZMk5+hOBkyjXFfKMF3H5wJ0uA8hadpelqgPuxinvjC/qBBbsbbvjcwl6JgmEjQ12TXF1GjnyhOPHce+0bnux6/tkJqfZH37Cn2W4+8uzbuRHUjscIEmCntxI0gyuWkU8XpSZb0u/o/VDUArBo3y6K1v4PES31im2aLWYt7mFuG9kpEns0rPRU/iQPsRt90aa+HN4P4qSHPJRKcVssaiknCwUiPq2y8lfILH5ihiyaeZHPpyHtidgEPXFvofzRRaKMc+4tS2846aToWZV6B0WMJghWnKY=
    - APPNAME="HCPush"
    - 'DEVELOPER_NAME="Apple Development: 鹏 盛 (59U3UW842N)"'
    - PROFILE_NAME="sdk_demo"



