os: osx
osx_image: xcode9
language: objective-c

xcode_project: Samples/HCPush.xcodeproj # path to your xcodeproj folder
xcode_scheme: HCPush
xcode_destination: platform=iOS Simulator,OS=13.5,name=iPhone X

